# Default values for catalog-comments-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##catalog-comments-service
CATALOG_COMMENTS_SERVICE_MEMORY: "500Mi"