# Default values for dataservice-publisher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

DATASERVICE_PUBLISHER_MEMORY: "200Mi"
PUBLISHER_URL: https://organization-catalogue.fellesdatakatalog.brreg.no/organizations
