apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fuseki
  name: fuseki
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fuseki
    spec:
      containers:
      - image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: fuseki
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_FUSEKI_SERVICE_MEMORY" .Values.FDK_FUSEKI_SERVICE_MEMORY | quote }}
        volumeMounts:
        - mountPath: /etc/fuseki/databases/
          name: fuseki-claim1
      restartPolicy: Always
      volumes:
      - name: fuseki-claim1
        persistentVolumeClaim:
          claimName: fuseki-claim0
status: {}