# Default values for dcat-ap-no-validator-cache.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#dcat-ap-no-validator-cache
DCAT_AP_NO_VALIDATOR_CACHE_MEMORY: "50Mi"