# Default values for fdk-nginx-registration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

FDK_NGINX_REGISTRATION_MEMORY: "10Mi"
FDK_NGINX_REGISTRATION_CPU: "1m"
