# Default values for concept-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##concept-catalog
CONCEPT_CATALOG_MEMORY: "2Gi"
CONCEPT_CATALOG_CPU: "200m"