# Default values for Elasticsearch7.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##elasticsearch7
FDK_ES_CLUSTERNAME: elasticsearch
FDK_ES_CLUSTERNODES: elasticsearch7:9300
FDK_ES_SECURITY: "false"
FDK_ES_MEMORY: "6100Mi"
ES7_IMAGE: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
ES5_BUSY_IMAGE: busybox:1.34.1