apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: publishers-cache
  name: publishers-cache
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publishers-cache
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: publishers-cache
    spec:
      containers:
        - env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
                key: PUBLISHERS_CACHE_PASSWORD
          name: publishers-cache
          image: redis:6.0.9-alpine
          imagePullPolicy: Always
          args: [ "--requirepass", "$(REDIS_PASS)", "--appendonly", "yes", "--save", "900", "1", "--save", "30", "1"]
          ports:
          - containerPort: 6379
            name: redis
          resources:
            requests:
              memory: {{ required "Missing value PUBLISHERS_CACHE_MEMORY" .Values.PUBLISHERS_CACHE_MEMORY | quote }}
          volumeMounts:
          - mountPath: /data
            name: publishers-cache-claim0
      restartPolicy: Always
      volumes:
      - name: publishers-cache-claim0
        persistentVolumeClaim:
          claimName: publishers-cache-claim0
status: {}