# Default values for dataservice-publisher-triplestore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##dataservice-publisher-triplestore
DATASERVICE_PUBLISHER_TRIPLESTORE_MEMORY: "850Mi"