# Default values for fdk-cms-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##fdk-cms-service
FDK_CMS_SERVICE_MEMORY: "300Mi"
FDK_CMS_SERVICE_CPU: "10m"
