apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dcat-ap-no-validator
  name: dcat-ap-no-validator
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcat-ap-no-validator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dcat-ap-no-validator
    spec:
      containers:
      - env:
        - name: ENV
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: NAMESPACE
        - name: FDK_REGISTRATION_BASE_URI
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: FDK_API_AUTHORIZATION_KEY
        - name: ADMIN_GUI_BASE_URI
          valueFrom:
            secretKeyRef:
              name: commonurl-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: ADMIN_GUI_BASE_URI
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: dcat-ap-no-validator
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value DCAT_AP_NO_VALIDATOR_MEMORY" .Values.DCAT_AP_NO_VALIDATOR_MEMORY | quote }}
      restartPolicy: Always
status: {}
