# Default values for fdk-publicservice-harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##fdk-publicservice-harvester
FDK_PUBLIC_SERVICE_HARVESTER_MEMORY: "750Mi"