# Default values for fdk-concept-harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##fdk-concept-harvester
FDK_CONCEPT_HARVESTER_MEMORY_REQ: "4Gi"
FDK_CONCEPT_HARVESTER_CPU_REQ: "1"
