# Default values for dcat-ap-no-validator-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##dcat-ap-no-validator-service
DCAT_AP_NO_VALIDATOR_SERVICE_MEMORY: "500Mi"
