# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

FDK_REASONING_SERVICE_CPU_REQ: "750m"
FDK_REASONING_SERVICE_MEMORY_REQ: "3000Mi"
FDK_REASONING_SERVICE_MEMORY_LIMIT: "3000Mi"
