# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

FDK_REASONING_SERVICE_MEMORY_REQ: "5000Mi"
FDK_REASONING_SERVICE_CPU_REQ: "150m"
FDK_REASONING_SERVICE_MEMORY_LIMIT: "6000Mi"
FDK_REASONING_SERVICE_CPU_LIMIT: "500m"
