# Default values for records of processing activities.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##records-of-processing-activities
RECORD_OF_PROCESSING_ACTIVITIES_MEMORY: "100Mi"