apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: altinn-model-publisher
  name: altinn-model-publisher
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: altinn-model-publisher
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: altinn-model-publisher
    spec:
      containers:
        name: altinn-model-publisher
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value ALTINN_MODEL_PUBLISHER_MEMORY" .Values.ALTINN_MODEL_PUBLISHER_MEMORY | quote }}
      restartPolicy: Always
status: {}
