# Default values for catalog-store.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##catalog-store
CATALOG_STORE_CLUSTERNAME: catalog-store
CATALOG_STORE_CLUSTERNODES: catalog-store:9300
CATALOG_STORE_SECURITY: "true"
CATALOG_STORE_MEMORY_REQ: "6Gi"
CATALOG_STORE_CPU_REQ: "500m"
CATALOG_STORE_MEMORY_LIMIT: "10Gi"
CATALOG_STORE_CPU_LIMIT: "2"
CATALOG_STORE_IMAGE: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
CATALOG_STORE_BUSY_IMAGE: busybox:1.36.1
