apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: fdk-fuseki-service
  name: fdk-fuseki-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-fuseki-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: fdk-fuseki-service
    spec:
      containers:
      - image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: fdk-fuseki-service
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value FDK_FUSEKI_SERVICE_MEMORY" .Values.FDK_FUSEKI_SERVICE_MEMORY | quote }}
        volumeMounts:
        - mountPath: /etc/fuseki/databases/
          name: fdk-fuseki-service-claim0
      restartPolicy: Always
      volumes:
      - name: fdk-fuseki-service-claim0
        persistentVolumeClaim:
          claimName: fdk-fuseki-service-claim0
status: {}