# Default values for fdk-dataset-harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##fdk-dataset-harvester
FDK_DATASET_HARVESTER_MEMORY: "4Gi"
FDK_DATASET_HARVESTER_CPU_REQ: "1"
