apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: dataservice-publisher-triplestore
  name: dataservice-publisher-triplestore
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: dataservice-publisher-triplestore
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: dataservice-publisher-triplestore
    spec:
      containers:
      - image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        name: dataservice-publisher-triplestore
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value DATASERVICE_PUBLISHER_TRIPLESTORE_MEMORY" .Values.DATASERVICE_PUBLISHER_TRIPLESTORE_MEMORY | quote }}
        volumeMounts:
        - mountPath: /etc/fuseki/databases/
          name: dataservice-publisher-triplestore-claim0
      restartPolicy: Always
      volumes:
      - name: dataservice-publisher-triplestore-claim0
        persistentVolumeClaim:
          claimName: dataservice-publisher-triplestore-claim0
status: {}