# Default values for PostgreSQL.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

FDK_POSTGRESQL_MEMORY: "10Mi"
FDK_POSTGRESQL_IMAGE: gcr.io/cloudsql-docker/gce-proxy:1.11