# Default values for PostgreSQL.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

FDK_POSTGRESQL_MEMORY: "20Mi"
FDK_POSTGRESQL_CPU: "2m"
FDK_POSTGRESQL_IMAGE: gcr.io/cloudsql-docker/gce-proxy:1.37.7
FDK_SQL: digdir-fdk
