# Default values for PostgreSQL.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

FDK_POSTGRESQL_MEMORY: "20Mi"
FDK_POSTGRESQL_CPU: "2m"
FDK_POSTGRESQL_IMAGE: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.17.1
FDK_SQL: digdir-fdk
