# Default values for dataset-catalog-gui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##dataset-catalog-gui
DATASET_CATALOG_GUI_MEMORY: "10Mi"
DATASET_CATALOG_GUI_CPU: "1m"
