# Default values for fdk-dataset-preview-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##fdk-dataset-preview-service
FDK_DATASET_PREVIEW_SERVICE_MEMORY: "750Mi"