# Default values for fdk-informationmodel-harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##fdk-informationmodel-harvester
FDK_INFORMATIONMODEL_HARVESTER_MEMORY: "3000Mi"