# Default values for fdk-public-service-harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##fdk-public-service-harvester
FDK_PUBLIC_SERVICE_HARVESTER_MEMORY: "750Mi"