apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: a-back-end-service
  name: a-back-end-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: a-back-end-service
    spec:
      containers:
      - env:
        - name: MONGO_USERNAME
          value: {{ required "Missing value MONGO_USERNAME" .Values.MONGO_USERNAME }}
        - name: MONGO_PASSWORD
          value: {{ required "Missing value MONGO_PASSWORD" .Values.MONGO_PASSWORD }}
        - name: MONGO_HOST
          value: {{ required "Missing value MONGO_HOST" .Values.MONGO_HOST }}
        name: a-back-end-service
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value TEMPLATE_SERVICE_MEMORY" .Values.TEMPLATE_SERVICE_MEMORY | quote }}
      restartPolicy: Always
status: {}
