# Default values for dcat-ap-no-validator-gui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#dcat-ap-no-validator-gui
DCAT_AP_NO_VALIDATOR_GUI_MEMORY: "10Mi"