# Default values for records of processing activities gui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##a-template-service (api)
RECORD_OF_PROCESSING_ACTIVITIES_GUI_MEMORY: "1000Mi"